language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: TYPO3=dev-master PHPUNIT_TESTS=yes
    - php: 7.2
      env: TYPO3=^9.0 PHPUNIT_TESTS=yes PHP_LINT=yes
    - php: 7.2
      env: TYPO3=^8.0 PHPUNIT_TESTS=yes
    - php: 7.2
      env: TYPO3=^7.6 PHPUNIT_TESTS=yes
    - php: 7.1
      env: TYPO3=^8.0 PHPUNIT_TESTS=yes PHP_LINT=yes
    - php: 7.1
      env: TYPO3=^8.0 CODE_ANALYSIS=yes
    - php: 7.1
      env: TYPO3=^7.6 PHPUNIT_TESTS=yes
    - php: 7.1
      env: TYPO3=^7.6 CODE_ANALYSIS=yes
    - php: 7.0
      env: TYPO3=^8.0 PHPUNIT_TESTS=yes PHP_LINT=yes
    - php: 7.0
      env: TYPO3=^8.0 CODE_ANALYSIS=yes
    - php: 7.0
      env: TYPO3=^7.6 PHPUNIT_TESTS=yes
    - php: 7.0
      env: TYPO3=^7.6 CODE_ANALYSIS=yes
    - php: 5.6
      env: TYPO3=^7.6 PHPUNIT_TESTS=yes PHP_LINT=yes
    - php: 5.5
      env: TYPO3=^7.6 PHPUNIT_TESTS=yes PHP_LINT=yes
  allow_failures:
    - env: TYPO3=dev-master PHPUNIT_TESTS=yes
    - env: TYPO3=dev-master CODE_ANALYSIS=yes
    - env: TYPO3=^8.0 CODE_ANALYSIS=yes
    - env: TYPO3=^7.6 CODE_ANALYSIS=yes

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

before_script:
  - >
    if [ "$TYPO3" == "dev-master" ]; then
      composer config minimum-stability dev;
      composer require typo3/cms-backend="dev-master" --no-update;
      composer require typo3/cms-core="dev-master" --no-update;
    fi
  - composer require nimut/typo3-complete="$TYPO3"
  - mkdir -p .Build/Web/typo3conf/ext/
  - if [ ! -L .Build/Web/typo3conf/ext/content_defender ]; then ln -snvf ../../../../. .Build/Web/typo3conf/ext/content_defender; fi
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    if [ "$PHPUNIT_TESTS" == "yes" ]; then
      echo;
      echo "Running functional tests";
      echo;
      echo;
      export typo3DatabaseName="typo3";
      export typo3DatabaseHost="localhost";
      export typo3DatabaseUsername="root";
      export typo3DatabasePassword="";
      find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml {}';
    fi

  - >
    if [ "$CODE_ANALYSIS" == "yes" ]; then
      travis_fold start before_phpstan;
      travis_time_start;
      echo;
      echo "Running php static analysis";
      echo;
      echo;
      composer require phpstan/phpstan=^0.9 --update-with-dependencies
      travis_time_finish;
      travis_fold end before_phpstan;
      .Build/bin/phpstan analyse -c .phpstan.neon --level 5 Classes Tests;
    fi

  - >
    if [ "$PHP_LINT" == "yes" ]; then
      echo;
      echo "Running php lint";
      echo;
      echo;
      find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;
    fi
